[package]
name = "tokenizers-c"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]

tokenizers = { version = "0.21.0", default-features = false, features = ["onig"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
